services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - ALLOWED_FILE_TYPES=epub,pdf,mobi,azw,azw3,txt,fb2,cbr,cbz
      - RUST_LOG=info
    volumes:
      - ./uploads:/uploads
      - ./backend:/app
    working_dir: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app

volumes:
  uploads:
